version: '2'
services:
  puppeteer-crawler:
    image: weihanli/puppeteer:latest
    container_name:  puppeteer-crawler
    user: 1000:1000
    ports:
      - 10240:3000
    volumes:
      - ./src:/app
    command: >
      bash -c "npm install
      && npm run start"